### ISSUE TITLE
Implement a function that ensures a given contract is ERC721 compliant 

### ISSUE THREAD

**Issue by josealonso** [ReleaseClub/contracts#10]
Quoting @neatonk 
```
you'd be doing a cross contract call to the `supportsInterface` function on the provided contractAddress. 
Lookup the ERC721 spec and see what value to pass to detect support for the ERC721 Interface
```

**Comment by neatonk** [comment]
Thanks @josealonso this is very helpful.

**Comment by josealonso** [comment]
The caveat is that many/some NFT contracts don't have the `supportInterface` function.

**Comment by neatonk** [comment]
That might actually be helpful, because per the spec, an ERC721 includes the `supportsInterface` function. So if it doesn't have it or it fails when you try it, it's not an ERC721.

**Comment by josealonso** [comment]
> That might actually be helpful, because per the spec, an ERC721 includes the `supportsInterface` function. So if it doesn't have it or it fails when you try it, it's not an ERC721.

`interface IERC721 is IERC165 {` 
This is OpenZeppelin's, although it wasn't like that in 2018. 
But yeah, I will check the contract includes the `supportInterface` function.

EDIT: I was referring to ERC20 tokens. In 2018 that function wasn't included.
