### ISSUE TITLE
Consider Lanyard for club allowlist and/or membership

### ISSUE THREAD

**Issue by neatonk** [ReleaseClub/contracts#16]
[Lanyard](http://lanyard.build) creates a merkle root for a set of addresses. This could be used to create a club with a large number of addresses on the allowlist for a low fixed cost. 

This merkle root could be used to represent membership or it could be used to gate membership via an NFT mint or another transaction. In either case this minimizes the upfront cost and allows members to initiate and bear the cost of the transaction in which they become a member of a club.

**Comment by josealonso** [comment]
> [Lanyard](http://lanyard.build) creates a merkle root for a set of addresses. This could be used to create a club with a large number of addresses on the allowlist for a low fixed cost.
> 
> This merkle root could be used to represent membership or it could be used to gate membership via an NFT mint or another transaction. In either case this minimizes the upfront cost and allows members to cover initiate and bear the cost of the transaction in which they become a member of a club.

I didn't know this tool. I wrote a small contract to airdrop tokens using a Merkle tree, but this tool speeds up the development process, specially because the provided API allows to communicate backend and frontend. 
Very good finding, @neatonk !!

**Comment by neatonk** [comment]
Thanks @josealonso! This is a new tool—I think this one was mentioned in a newsletter I read. Very cool to hear that you've some experience with this process via your own airdrop contract.

**Comment by neatonk** [comment]
After some thought, I think this could be supported optionally via the UI, but not tied to our contracts in anyway. Instead, this feature can be externalized by allowing a club use an existing token for membership.

**Comment by josealonso** [comment]
> After some thought, I think this could be supported optionally via the UI, but not tied to our contracts in anyway. Instead, this feature can be externalized by allowing a club use an existing token for membership.

This issue could be on the backlog if we want to give an airdrop service at some point. 
As far as I saw, this *lanyard* tool together with the *[mint.fun](https://mint.fun)* web page make airdropping a not so difficult task.
