### ISSUE TITLE
Use existing token for membership

### ISSUE THREAD

**Issue by neatonk** [ReleaseClub/contracts#17]
## Rationale

In the existing contracts, members are stored in an array belonging to the club contract. This allows us complete control of the logic surrounding membership but limits composability. By allowing external tokens to be used for membership, we pass this control to the club owner.

To make it easy to get started, we can allow a club to be created without a membership token—in which case only the owner will have write access. We can also provide instructions for creating and distributing a membership token via https://create.zora.co and may consider an integration to make this super easy.

## Requirements

- Allow each club to provide the address of an existing ERC721 or ERC20 token address and a minimum balance.
- Create a function modifier that checks the token balance of `msg.sender` to assert that the token balance is high enough.
- Use the modifier to limit access to privileged functions such as those used to create a new release.

Replaces #16.

**Comment by josealonso** [comment]
@neatonk, this issue title is clear.
But I don't understand the first paragraph of the Rationale. Members are not stored anywhere. It just happens that a temporary array is built when someone wants to retrieve the members of a given club. That's what the `viewMembers` function does.
