### ISSUE TITLE
A club should consist of one or more seasons

### ISSUE THREAD

**Issue by neatonk** [ReleaseClub/contracts#18]
## Rationale

There is currently no way to distinguish a clubs members and releases over time—they all flow together into a single stream. Instead, we can use the concept of seasons to create one or more bounded groupings of releases, along with the context in which they were created. This allows the identity of the club to evolve from season-to-season and preserves a record of that evolution in the context surrounding each season.

## Requirements
- Each club acts as a season factory which deploys season contracts.
- Only the club owner can create a new season.
- Each club may have only one active season at a time.
- Each season has it's own membership token address.
- The same membership address may be used for more than one season, but this is not encouraged.
- Every release belongs to a season—releases are no longer added to the club directly.
- A club may optionally be created with an initial season.
- Each season can be bounded in time, release quantity, or manually via a function call to close the season—similar to Zora editions.
- Each season must have a title as this will be used in the club UI. 
- Each season may have a description and image URI to provide additional context in the UI.

## Questions
- **Would it be better to allow an NFT to be used to provide additional context for each season?** If so, the description and image URI could be provided by the NFT. I'm not sure if this would offer any concrete advantage.
- **Does the initial season need to be treated specially?** E.g. to avoid overwhelming new club owners or to support clubs which will only have one season.
- **Would it make sense to allow overlapping seasons or would this be confusing/complicated**

**Comment by josealonso** [comment]
@neatonk, I think this issue is about having multiple copies of the club (main contract). These copies are small contracts that have the minimum code to forward the calls to the main contracts. These clones have only state variables referring to one single club, but all the functions are on the main contract, which is `ReleaseClub` in our case. This is called a minimal proxy and it's what I tried  to deploy yesterday using the **Clones** library.

**Comment by josealonso** [comment]
> @neatonk, I think this issue is about having multiple copies of the club (main contract). These copies are small contracts that have the minimum code to forward the calls to the main contracts. These clones have only state variables referring to one single club, but all the functions are on the main contract, which is `ReleaseClub` in our case. This is called a minimal proxy and it's what I tried to deploy yesterday using the **Clones** library. Related to #14. The branch is called _reduce-size_, because a minimal proxy is such a small contract that you save a lot of gas. Probably the branch name is not as significant as it should be. Sorry about that.

Ups, sorry, I realized this doesn't have to with proxies, as I said in my previous comment.

**Comment by josealonso** [comment]
> ## Rationale
> 
> There is currently no way to distinguish a clubs members and releases over time—they all flow together into a single stream. Instead, we can use the concept of seasons to create one or more bounded groupings of releases, along with the context in which they were created. This allows the identity of the club to evolve from season-to-season and preserves a record of that evolution in the context surrounding each season.
> ## Requirements
> 
>     * Each club acts as a season factory which deploys season contracts.
> 
>     * Only the club owner can create a new season.
> 
>     * Each club may have only one active season at a time.
> 
>     * Each season has it's own membership token address.
> 
>     * The same membership address may be used for more than one season, but this is not encouraged.
> 
>     * Every release belongs to a season—releases are no longer added to the club directly.
> 
>     * A club may optionally be created with an initial season.
> 
>     * Each season can be bounded in time, release quantity, or manually via a function call to close the season—similar to Zora editions.
> 
>     * Each season must have a title as this will be used in the club UI.
> 
>     * Each season may have a description and image URI to provide additional context in the UI.
> 
> 
> ## Questions
> 
>     * **Would it be better to allow an NFT to be used to provide additional context for each season?** If so, the description and image URI could be provided by the NFT. I'm not sure if this would offer any concrete advantage.
> 
>     * **Does the initial season need to be treated specially?** E.g. to avoid overwhelming new club owners or to support clubs which will only have one season.
> 
>     * **Would it make sense to allow overlapping seasons or would this be confusing/complicated**

@neatonk, some questions:

- How many seasons does a club have ?
- Does every season have a different NFT ?

**Comment by josealonso** [comment]
I'm sorry I don't understand these requirements.

**Comment by neatonk** [comment]
No worries. This issue and others I've added recently are here for discussing potential features and requirements for the MVP mainnet launch of release club. These issues are not intended as marching orders for anyone and are not ready to be implemented. 

To answer your questions:

- A club would start with one season, but there is no limit to the number of season's a club can have.
- Every season would be associated with a membership NFT provided by the club owner. It's up to the owner to decide if each season should have it's own membership NFT or not.

Thanks for reading through these issues and asking questions. It has been very helpful.

**Comment by neatonk** [comment]
I also see seasons as a natural way to introduce new features and updates by deploying new contracts for future seasons. As a bonus, this would likely make it unnecessary for the club or season contracts to be upgradeable.

**Comment by neatonk** [comment]
> Each club acts as a season factory which deploys season contracts.

This requirement is debatable. As an alternative, we could allow the club owner to deploy a season contract and then add it to the club. This may require more checks and would benefit form a well defined interface which season contracts are required to implement. A registry of supported season contracts could be used instead of an interface, a la Zora's V3 module registry.
