### ISSUE TITLE
Determine the amount of Ether needed to create a club

### ISSUE THREAD

**Issue by josealonso** [ReleaseClub/contracts#20]
The `addClub` function in the factory contract is **payable**, meaning that any amount greater than zero Ethers is needed to create a club. 
That amount of Ethers must be a fixed quantity, the same way it's done when you buy an NFT.

**Comment by josealonso** [comment]
This quantity depends on the business model. Technically it's just one line.

**Comment by neatonk** [comment]
Ah, thanks for pointing this out. The cost to create a club should be free + gas. Charging a fee would only provide an incentive for others to deploy their own ClubFactory.

**Comment by josealonso** [comment]
> Ah, thanks for pointing this out. The cost to create a club should be free + gas. Charging a fee would only provide an incentive for others to deploy their own ClubFactory.

That makes sense. This calculation is not trivial then. I'll look into it when I have time. 
Which are the highest priority tasks before deploying on mainnet ?

**Comment by josealonso** [comment]
> > Ah, thanks for pointing this out. The cost to create a club should be free + gas. Charging a fee would only provide an incentive for others to deploy their own ClubFactory.
> 
> That makes sense. This calculation is not trivial then. I'll look into it when I have time. Which are the highest priority tasks before deploying on mainnet ?

We don't need to calculate anything. if a fee is not going to be charged, then the function should **not** be **payable**.

**Comment by neatonk** [comment]
Thanks. This matches my understanding too. There should be no payable functions in the any of these contracts and any transaction with a value should revert. I've created a new issue to track this.

**Comment by neatonk** [comment]
> Which are the highest priority tasks before deploying on mainnet ?

I'm collecting tasks here. Not quite ready to prioritize and dig in yet.
