### ISSUE TITLE
All contracts and functions should be non-payable

### ISSUE THREAD

**Issue by neatonk** [ReleaseClub/contracts#21]
## Rationale

Since our contracts are not charging a fee, they should not include any payable functions.  See #20 for context.

## Requirements

- No `payable` functions exist.
- Transactions including a value should revert. This is the default behavior for non-payable funcitons.

## Steps to complete

- Ensure `payable` has been removed from all function declarations.
- For each contract, add tests to confirm that transactions including a value revert for:
  - the built in `transfer` and `send` methods
  - the contract constructor

**Comment by josealonso** [comment]
I think I understand you, @neatonk

**Comment by neatonk** [comment]
Cool. I wrote this up as reminder to ensure this addressed before deploying to mainnet. Nothing needs to be done yet, but conversation is welcome as needed for clarification.
