### ISSUE TITLE
Use the Goerli testnet

### ISSUE THREAD

**Issue by josealonso** [ReleaseClub/contracts#23]
The **Rinkeby** testnet is being used right now, like in many other projects.
But Rinkeby is deprecated, the alchemy faucet recently stopped working and **Zora** has deployed its contracts on Goerli, according to what I read on its discord server.

**Comment by neatonk** [comment]
Awesome, thanks for the adding this. Should be straight forward to update the deploy scripts and UI to point at Goerli.
