### ISSUE TITLE
ReleaseClubFactory Contract

### ISSUE THREAD

**Issue by neatonk** [ReleaseClub/contracts#3]
# Factory must:
- [x] be [ownable](https://docs.openzeppelin.com/contracts/4.x/api/access#Ownable).
- [x] be [pausable](https://docs.openzeppelin.com/contracts/4.x/api/security#Pausable).

## Owner must be able to:
- [x] deploy new release club contracts (See #1 )
- [x] initialize a new club contract
- [x] pause the contract to prevent future deploys.

## Events
- [x] emit CreatedClub(address indexed clubAddress) when new club is created. (not sure if additional unindexed field would be useful here).

**Comment by neatonk** [comment]
The factory contract does NOT need to store the addresses of the contracts it creates. The emitted event is what will be used to enumerate clubs when indexing for inclusion e.g. in spinamp.

**Comment by neatonk** [comment]
Upgradability is not important here, but would be nice.

**Comment by josealonso** [comment]
> Upgradability is not important here, but would be nice.

I can try to use a minimal proxy pattern. I implemented a token generator app, but it's not optimized. The app is deployed here https://my-web3-boilerplate.vercel.app/

**Comment by neatonk** [comment]
Thanks for offering. Let's keep it simple and not make this one upgradable.

**Comment by josealonso** [comment]
I'm making the contract `pausable` using OpenZeppelin's *Pausable* contract.

**Comment by josealonso** [comment]
I just opened a PR to make the contract pausable. I think this issue can be closed if my PR is accepted, @neatonk .The rest of the features were implemented by @dhruv035 .
