### ISSUE TITLE
Package our contracts repo

### ISSUE THREAD

**Issue by neatonk** [ReleaseClub/contracts#5]
We should package our contracts repo so it can be included in the ui as a dependency rather than copy/paste files. This will be important because we are encouraging people to fork the repo.

Publish to: https://www.npmjs.com/org/releaseclub
- - -
Example: https://github.com/ourzora/zora-drops-contracts

**Comment by dhruv035** [comment]
we would want something like this repo to package for front end https://github.com/dhruv035/aave-utilities/tree/master/packages/contract-helpers
